### ISSUE TITLE
Switch to using Thunderforest Outdoors tiles

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-youth-project#2]

**Comment by ColmMassey** [comment]
Upgrade to use latest version of sea-map and and select the Thunderforest theme.

https://dev.ica-youth-network.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
@wu-lee can you see this message?

**Comment by ColmMassey** [comment]
This repository seems to have been set up differently to others of its ilk.

**Comment by wu-lee** [comment]
Yes I can see it, @ColmMassey

**Comment by ColmMassey** [comment]
Did you change something, as I can now assign you to this, where I couldn't before?!?!

How easy is it for you to push the latest sea-map to this dev project and to point to the Thunderdome?

**Comment by wu-lee** [comment]
No, all I did was post!  Perhaps that adds me as a contributor somehow?

I've updated and redeployed it to https://dev.ica-youth-network.solidarityeconomy.coop/

However:
- it still uses w3id.solidarityeconomy.coop PURIs
- it still uses sea-0 as the static data source
- it still uses sea-0 for SPARQL queries
- there is no dev/prod split

So I've just made minimal fixes to get it to work as-is (plus some misc tidying).

There is one more problem, possibly related to the problem you mention above: I don't have write permissions to this repository, so I can't push the code online.  Can you assign "admin" privs to the "developer" team?

**Comment by wu-lee** [comment]
Now also switched to Thunderforest. I assume you mean that rather than the Dutch gabber festival or Aunty Entity's gladiatorial arena...

**Comment by ColmMassey** [comment]
> No, all I did was post! Perhaps that adds me as a contributor somehow?

It wasn't in the list of repositories that the Developer Team had access too. It's in there now.

> Aunty Entity's gladiatorial arena...

That was more where my mind was wandering. Perhaps post no deal Brexit with make such sporting delights more likely.

**Comment by ColmMassey** [comment]
> There is one more problem, possibly related to the problem you mention above: I don't have write permissions to this repository, so I can't push the code online. Can you assign "admin" privs to the "developer" team?

Did my changes resolve this issue? Should I be able to see it now?

**Comment by wu-lee** [comment]
Doesn't seem to have, no.

**Comment by ColmMassey** [comment]
> If i=only it was that simple...
Can you be more specific, when you say 'perms'?

**Comment by ColmMassey** [comment]
Actually. Spotted another glaring difference. Try now.

**Comment by wu-lee** [comment]
Ah yes, works now, thanks. Code pushed.
