### ISSUE TITLE
Update ICA youth map data

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/ica-youth-project#3]
Colm asked:
> Can you update the Youth map at your convenience?

Gretchen Hacquard said:
> I finally was able to get the coop youth map imported into our database and updated for this map: https://www.globalyouth.coop/en/projects/mapping-youth-coops-support-initiatives

 There is a data file which I've put into the Nextcloud folder as `ICA/ica-youth-2021-07-28.csv`

**Comment by wu-lee** [comment]
Note: schema has changed again, will need to create a new schema.yml file and check the conversion rules.

**Comment by ColmMassey** [comment]
Prioritising updating ICA members map over youth map.

**Comment by ColmMassey** [comment]
Looks like we have lost the code which handles the Qualifier _Coop Promoter/Supporter_ in the latest ICA members upload.
If you look at the newest entry 43855, it has the Coop Promoter/Supporter. And for the ICA map dialog, this is interpreted as an Option in Structure.

**Comment by ColmMassey** [comment]
Do you guys think I'm correct that we lost this code when we added the multi-language support? Is it easy to add back in?

**Comment by ColmMassey** [comment]
> Looks like we have lost the code which handles the Qualifier _Coop Promoter/Supporter_ in the latest ICA members upload.
> If you look at the newest entry 43855, it has the Coop Promoter/Supporter. And for the ICA map dialog, this is interpreted as an Option in Structure.

Any thoughts on this one guys? Need to get back to ICA on it.

**Comment by wu-lee** [comment]
Looking, the `standard.csv` entry for 43855 gets a qualifier value of "Coop Promoter/Supporter", so that step seems to be working, I think?

In the ICA map on dev, the same initiative is shown with these fields:

> Structure Type: Company (Other)
> Typology: undefined
> Economic Activity: All

There is special logic for handling this in the ICA map site, in `popup.js`,,, it seems insert "Structure Type: " plus the vocab name for the qualifier after the main structure type.  But, it's looking up an activity vocab index using a qualifier term name, which won't work.  In fact, I can't see a qualifier vocab index in the supplied vocab data at all.

So yes, I think it's probably broken, but I'm puzzled why it's got the value it did - I think I'll have to dig around more.

**Comment by wu-lee** [comment]
Ok,.. I see - it was the multilanguages support work which touched this.  I think it'll be fairly easy to rectify.

**Comment by wu-lee** [comment]
Ok, I've deployed a rough working version of ICA with the Qualifier logic restored on dev-1. I've also tied the code (it's gnarly!) and fixed some `undefined` values showing up in the typology field.

As part of this work, we now have the beginnings of a test framework for sea-map, which was a bit tricky to set up (mainly because the code assumes it is running in the browser), and to  the code is really not written to allow testing of parts of it without the rest of it coming along and complicating things.  However, I needed this to ensure I was not changing the ICA popup content except in the desired ways.

To check it works, look for 'Hikari' (which finds a coop supporter), and 'Yuva' (which finds a typology: other that used to be undefined).

There are some caveats:
- it's a bit slower because the qualifier vocab is loaded too
- the qualifier vocab and its terms doesn't show in the search dialogs. So you can't search for "coop supporters" or any other qualifier.
- I can see there's going to be problems with non-English, because 
  - the phrase "Secondary Activities" was hardwired still, and has no translations
  - the Qualifier vocab has only English term names.

**Comment by ColmMassey** [comment]
I think this will do for now. We can schedule translation extensions after schemas review.

**Comment by wu-lee** [comment]
Now integrated ICA Youth Network data from 28th July 2021 (AFAICT, same content, different CSV headers). ICA Youth map site will be showing it, but it should look the same, I think.

`schema.yml` and `converter` updated to be essentially identical to the ones for ICA.

There was a problem with map-sse, which wasn't redirecting files with no suffix to one with a .skos suffix, which took a little tracking down because there's some weird redirection going on in there. Seems like I must have broken it in an earlier refactor, it hasn't affected anything. Slightly puzzling that it didn't, however, will be looking into that.

**Comment by ColmMassey** [comment]
![image](https://user-images.githubusercontent.com/1162642/137172153-f3df4323-f0bc-4c58-b628-bd9b20323bb6.png)
